var namespaces_dup =
[
    [ "Error codes", "error_codes.html#autotoc_md4", [
      [ "File code", "error_codes.html#autotoc_md5", null ],
      [ "Error code translation", "error_codes.html#autotoc_md6", null ]
    ] ],
    [ "How it works", "how_it_works.html#autotoc_md7", [
      [ "Code structure and flow", "how_it_works.html#autotoc_md8", null ],
      [ "Rate replacement procedure", "how_it_works.html#autotoc_md9", null ]
    ] ],
    [ "alpha_decays.dat", "input_files.html#alpha_decays", null ],
    [ "beta_decay_marketin.dat", "input_files.html#bet_marketin", null ],
    [ "beta_decay_moeller.dat", "input_files.html#bet_moeller", null ],
    [ "beta_decay_reaclib.dat", "input_files.html#bet_reacl", null ],
    [ "chem_table.dat", "input_files.html#chemtable", null ],
    [ "datafile2.txt", "input_files.html#htpf", null ],
    [ "FISS_Mumpower", "input_files.html#fissmumpower", null ],
    [ "fissionrates_beta_delayed_mp22", "input_files.html#fissrates_bdel_mp22", null ],
    [ "fissionrates_beta_delayed_pa05", "input_files.html#fissrates_bdel_pa05", null ],
    [ "fissionrates_spontaneous", "input_files.html#fissrates_spont", null ],
    [ "fissionrates_n_induced", "input_files.html#fissrates_nind", null ],
    [ "frdm_sn.dat", "input_files.html#sn", null ],
    [ "stable_isotopes.txt", "input_files.html#stables", null ],
    [ "neunucleons.dat", "input_files.html#neunucleons", null ],
    [ "nu_channels", "input_files.html#nu_channels", null ],
    [ "nucross.dat", "input_files.html#nucross", null ],
    [ "nu_loss_data.dat", "input_files.html#nu_loss_data", null ],
    [ "rateseff.out", "input_files.html#ffn_rates", null ],
    [ "Reaclib_18_9_20", "input_files.html#reaclib", null ],
    [ "theoretical_weak_rates.dat", "input_files.html#ffn_rates2", null ],
    [ "winvne_v2.0.dat", "input_files.html#winvn", [
      [ "Fortran", "linux_install.html#fortran", null ],
      [ "Python", "linux_install.html#python", null ]
    ] ],
    [ "Using hdf5 files as output", "linux_install.html#hdf5", [
      [ "Issues", "mac_install.html#issues", null ]
    ] ],
    [ "absorption_eq", "namespaceabsorption__eq.html", null ],
    [ "alpha_decay", "namespacealpha__decay.html", null ],
    [ "alpha_decay_rate_module", "namespacealpha__decay__rate__module.html", null ],
    [ "alpha_network", "namespacealpha__network.html", null ],
    [ "analysis", "namespaceanalysis.html", null ],
    [ "analytic_mode", "namespaceanalytic__mode.html", null ],
    [ "benam_class", "namespacebenam__class.html", null ],
    [ "beta_decay_format", "namespacebeta__decay__format.html", null ],
    [ "beta_decay_rate_module", "namespacebeta__decay__rate__module.html", null ],
    [ "beta_eq", "namespacebeta__eq.html", null ],
    [ "bigbang", "namespacebigbang.html", null ],
    [ "bin", "namespacebin.html", "namespacebin" ],
    [ "charged-current_reaction", "namespacecharged-current__reaction.html", null ],
    [ "create_rates_grid", "namespacecreate__rates__grid.html", null ],
    [ "create_trajectories", "namespacecreate__trajectories.html", null ],
    [ "create_trajectory", "namespacecreate__trajectory.html", null ],
    [ "detailed_balance", "namespacedetailed__balance.html", null ],
    [ "effphase_class", "namespaceeffphase__class.html", null ],
    [ "emission_eq", "namespaceemission__eq.html", null ],
    [ "error_msg_class", "namespaceerror__msg__class.html", null ],
    [ "expand", "namespaceexpand.html", null ],
    [ "expansion_module", "namespaceexpansion__module.html", null ],
    [ "file_handling_class", "namespacefile__handling__class.html", null ],
    [ "fissfrag_custom", "namespacefissfrag__custom.html", null ],
    [ "fissfrag_kodtak", "namespacefissfrag__kodtak.html", null ],
    [ "fissfrag_kodtak_n_emission", "namespacefissfrag__kodtak__n__emission.html", null ],
    [ "fissfrag_mumpower", "namespacefissfrag__mumpower.html", null ],
    [ "fissfrag_mumpower_n_emission", "namespacefissfrag__mumpower__n__emission.html", null ],
    [ "fissfrag_panov", "namespacefissfrag__panov.html", null ],
    [ "fissfrag_panov_n_emission", "namespacefissfrag__panov__n__emission.html", null ],
    [ "fission_rate_module", "namespacefission__rate__module.html", null ],
    [ "fissrate_bdel", "namespacefissrate__bdel.html", null ],
    [ "fix_trajectory", "namespacefix__trajectory.html", null ],
    [ "flow", "namespaceflow.html", null ],
    [ "flow_module", "namespaceflow__module.html", null ],
    [ "format_class", "namespaceformat__class.html", null ],
    [ "gamma_eq", "namespacegamma__eq.html", null ],
    [ "gear_module", "namespacegear__module.html", null ],
    [ "global_class", "namespaceglobal__class.html", null ],
    [ "hdf5_format", "namespacehdf5__format.html", null ],
    [ "hdf5_module", "namespacehdf5__module.html", null ],
    [ "hydro_trajectory", "namespacehydro__trajectory.html", null ],
    [ "inter_module", "namespaceinter__module.html", null ],
    [ "jacobian_class", "namespacejacobian__class.html", null ],
    [ "ls_timmes_eos_module", "namespacels__timmes__eos__module.html", null ],
    [ "mergesort_module", "namespacemergesort__module.html", null ],
    [ "nc_cc_reaction", "namespacenc__cc__reaction.html", null ],
    [ "network_init_module", "namespacenetwork__init__module.html", null ],
    [ "neutral-current_reaction", "namespaceneutral-current__reaction.html", null ],
    [ "neutron-decay", "namespaceneutron-decay.html", null ],
    [ "neutron-decay-implicit-euler", "namespaceneutron-decay-implicit-euler.html", null ],
    [ "ni56-decay", "namespaceni56-decay.html", null ],
    [ "nse", "namespacense.html", null ],
    [ "nuclear_heating", "namespacenuclear__heating.html", null ],
    [ "nucstuff_class", "namespacenucstuff__class.html", null ],
    [ "nuflux_class", "namespacenuflux__class.html", null ],
    [ "parameter_class", "namespaceparameter__class.html", null ],
    [ "pardiso_class", "namespacepardiso__class.html", null ],
    [ "parser_module", "namespaceparser__module.html", null ],
    [ "plot_hdf5", "namespaceplot__hdf5.html", null ],
    [ "Plot_me", "namespacePlot__me.html", null ],
    [ "prepared_network", "namespaceprepared__network.html", null ],
    [ "reaclib_rate_module", "namespacereaclib__rate__module.html", null ],
    [ "read_neutrino", "namespaceread__neutrino.html", null ],
    [ "read_seeds", "namespaceread__seeds.html", null ],
    [ "read_trajectory", "namespaceread__trajectory.html", null ],
    [ "readini", "namespacereadini.html", null ],
    [ "ref_nsm", "namespaceref__nsm.html", null ],
    [ "rprocess-noheating", "namespacerprocess-noheating.html", null ],
    [ "screening", "namespacescreening.html", null ],
    [ "screening_module", "namespacescreening__module.html", null ],
    [ "single_zone_vars", "namespacesingle__zone__vars.html", null ],
    [ "switch_evolution", "namespaceswitch__evolution.html", null ],
    [ "tabulated_rate_module", "namespacetabulated__rate__module.html", null ],
    [ "tabulated_rates", "namespacetabulated__rates.html", null ],
    [ "tabulated_rates_custom_grid", "namespacetabulated__rates__custom__grid.html", null ],
    [ "thermal_neutrino_module", "namespacethermal__neutrino__module.html", null ],
    [ "timestep_module", "namespacetimestep__module.html", null ],
    [ "timmes_eos_module", "namespacetimmes__eos__module.html", null ],
    [ "tw_rate", "namespacetw__rate.html", null ],
    [ "tw_rate_module", "namespacetw__rate__module.html", null ],
    [ "ulimit", "namespaceulimit.html", null ],
    [ "units_module", "namespaceunits__module.html", null ],
    [ "winnet_monitor_failed", "namespacewinnet__monitor__failed.html", null ],
    [ "winnet_monitor_run", "namespacewinnet__monitor__run.html", null ],
    [ "winnse_module", "namespacewinnse__module.html", null ]
];